title: MaxPreps BB Stats
description: Documentation for the Colorado High School Baseball Projection System

# --- THEME SETTINGS ---
# We use remote_theme so you don't need a Gemfile
remote_theme: just-the-docs/just-the-docs

# --- PLUGINS (REQUIRED) ---
plugins:
  - jekyll-remote-theme

# --- SITE SETTINGS ---
url: https://timcoultas.github.io
baseurl: /maxpreps_bb_stats

# --- NAVIGATION & UI ---
back_to_top: true
search_enabled: true
heading_anchors: true

# --- FOOTER ---
footer_content: "Copyright &copy; 2025 Tim Coultas"